language: node_js
node_js:
  - 12.16.2
cache: npm
install:
  - npm ci
script:
  - sonar-scanner -Dsonar.verbose=true -X
  - npm test
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: dist/ng-tdd-ci-sq
  on:
    branch: master
addons: 
sonarcloud:
  organization: raloliver

env:
  global:
    secure: "$SONAR_TOKEN"
