env:
  global:
    secure: "$SONAR_TOKEN"
language: node_js
disty: trusty
node_js:
  - 12.16.2
cache: npm
addons: 
  sonarcloud:
    organization: raloliver
branches:
  only:
    - master
install:
  - npm ci
script:
  - npm test
  - npm run buildgp
  - sonar-scanner
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: dist/ng-tdd-ci-sq
  on:
    branch: master
