language: node_js
disty: trusty
node_js:
  - 12.16.2
cache: npm
addons: 
  sonarcloud:
    organization: raloliver
branches:
  only:
    - master
install:
  - npm ci
script:
  - sonar-scanner -Dsonar.verbose=true -X
  - npm test
  - npm run buildgp
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local_dir: dist/ng-tdd-ci-sq
  on:
    branch: master

# env:
#   global:
#     secure: "$SONAR_TOKEN"
