language: node_js
node_js: 
- 12.16.2
cache: npm

# before_install:
install:
  - npm ci
# before_script:
script:
  - npm test
  - npm run build
# after_success:
# after_failure:
# after_script:
# before_deploy:
deploy:
  - provider: pages
  - edge: true
  - skip-cleanup: true
  - github-token: $GITHUB_TOKEN
  - local_dir: build
  - on: 
      branch: master
# after_deploy:


